//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class CHATBOX
    {
        public int id { get; set; }
        public int idCustomer { get; set; }
        public int idAssistant { get; set; }
        public string content { get; set; }
        public Nullable<int> isSend { get; set; }
        public Person Customer
        {
            get
            {
                Person cus = DataProvider.ins.DB.PEOPLE.Find(this.idCustomer);
                return cus;

            }
            set { }
        }
        public Person Assistant
        {
            get
            {
                Person ass = DataProvider.ins.DB.PEOPLE.Find(this.idAssistant);
                return ass;

            }
            set { }
        }
        public Person Sender
        {
            get
            {
                if (this.isSend == 0)
                {
                    return Assistant;
                }
                return Customer;

            }
            set { }
        }
        public Visibility visibility2
        {
            get
            {
                if (this.isSend == 1)
                {
                    return Visibility.Collapsed;
                }
                return Visibility.Visible;

            }
            set { }
        }
        public Visibility visibility1
        {
            get
            {
                if (this.isSend == 0)
                {
                    return Visibility.Collapsed;
                }
                return Visibility.Visible;

            }
            set { }
        }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
