//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTOFPRODUCTBUY
    {
        public int id { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idReceipt { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
    
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
