//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_ShOPPING_NEWEntities1 : DbContext
    {
        public E_ShOPPING_NEWEntities1()
            : base("name=E_ShOPPING_NEWEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CART> CARTs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CHATBOX> CHATBOXes { get; set; }
        public virtual DbSet<CREDITCARD> CREDITCARDs { get; set; }
        public virtual DbSet<DELIVERY> DELIVERies { get; set; }
        public virtual DbSet<DISCOUNT> DISCOUNTs { get; set; }
        public virtual DbSet<IMAGE> IMAGES { get; set; }
        public virtual DbSet<LISTOFPRODUCTBUY> LISTOFPRODUCTBUYs { get; set; }
        public virtual DbSet<MANAGEPRODUCTSYSTEM> MANAGEPRODUCTSYSTEMs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<ORDERSRECEIPT> ORDERSRECEIPTs { get; set; }
        public virtual DbSet<PAYMENTINFORMATION> PAYMENTINFORMATIONs { get; set; }
        public virtual DbSet<Person> PEOPLE { get; set; }
        public virtual DbSet<PEOPLEINFO> PEOPLEINFOes { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTRATE> PRODUCTRATEs { get; set; }
        public virtual DbSet<PRODUCTTECHNICAL> PRODUCTTECHNICALs { get; set; }
        public virtual DbSet<RECEIPT> RECEIPTs { get; set; }
        public virtual DbSet<RECEIVERINFORMATION> RECEIVERINFORMATIONs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
