//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERSRECEIPT
    {
        public int idReceipt { get; set; }
        public int idOrder { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual ORDER ORDER1 { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
        public virtual RECEIPT RECEIPT1 { get; set; }
    }
}
