//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERSRECEIPTs = new HashSet<ORDERSRECEIPT>();
            this.ORDERSRECEIPTs1 = new HashSet<ORDERSRECEIPT>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCart { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> status { get; set; }
        public int idReceipt
        {
            get
            {
                ORDERSRECEIPT receipt = DataProvider.ins.DB.ORDERSRECEIPTs.Where(p => p.idOrder == this.id).FirstOrDefault();
                return receipt.idReceipt;

            }
            set { }
        }
        public double productPrice
        {
            get
            {
                PRODUCT p = DataProvider.ins.DB.PRODUCTs.Where(p1 => p1.id == this.idProduct).FirstOrDefault();
                return (double)p.price;

            }
            set { }
        }
        public int idProductType
        {
            get
            {
                PRODUCT p = DataProvider.ins.DB.PRODUCTs.Where(p1 => p1.id == this.idProduct).FirstOrDefault();
                return (int)p.idCategory;

            }
            set { }
        }
        public string productType
        {
            get
            {
                PRODUCT p = DataProvider.ins.DB.PRODUCTs.Where(p1 => p1.id == this.idProduct).FirstOrDefault();
                CATEGORY category = DataProvider.ins.DB.CATEGORies.Where(c1 => c1.id == p.idCategory).FirstOrDefault();
                return category.type;

            }
            set { }
        }
        public double total
        {
            get
            {
                return (double)this.quantity * productPrice;

            }
            set { }
        }
        public bool check { get; set; }
        public string prodductName
        {
            get
            {
                PRODUCT p = DataProvider.ins.DB.PRODUCTs.Where(p1 => p1.id == this.idProduct).FirstOrDefault();
                return p.name;

            }
            set { }
        }
        public string productImage
        {
            get
            {
                PRODUCT p = DataProvider.ins.DB.PRODUCTs.Where(p1 => p1.id == this.idProduct).FirstOrDefault();
                return p.thumbnailimage;

            }
            set { }
        }
        public string statusAppear
        {
            get
            {
                if (status == 1)
                {
                    return "Prepare product";
                }
                else if (status == 2)
                {
                    return "In delevery";
                }
                return "";
            }
            set { }
        }
        public virtual CART CART { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERSRECEIPT> ORDERSRECEIPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERSRECEIPT> ORDERSRECEIPTs1 { get; set; }
    }
}
