//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTINFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENTINFORMATION()
        {
            this.PEOPLEINFOes = new HashSet<PEOPLEINFO>();
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public int id { get; set; }
        public Nullable<int> typeOfCard { get; set; }
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> expDate { get; set; }
        public string ownName { get; set; }
        public string csv { get; set; }
    
        public virtual CREDITCARD CREDITCARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEOPLEINFO> PEOPLEINFOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
