//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEOPLEINFO
    {
        public int id { get; set; }
        public int idCustomer { get; set; }
        public Nullable<int> idReceiverInfo { get; set; }
        public Nullable<int> idPaymentOption { get; set; }
    
        public virtual PAYMENTINFORMATION PAYMENTINFORMATION { get; set; }
        public virtual Person Person { get; set; }
        public virtual RECEIVERINFORMATION RECEIVERINFORMATION { get; set; }
    }
}
