//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTTECHNICAL
    {
        public int id { get; set; }
        public Nullable<int> idProduct { get; set; }
        public string nameOfAttribute { get; set; }
        public string content { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
